### ISSUE TITLE
哈哈哈老哥强啊

### ISSUE THREAD

**Issue by ForeverOpp** [TobisLee/jlu-bath-booking#1]
我本来想写一个，但是之前写了东西发现github上已经有大佬实现了就搜着看看，果然已经有大佬实现了哈哈。

**Comment by ForeverOpp** [comment]
不过其实查的不严，修改html元素或者p图就可以混过去

**Comment by ForeverOpp** [comment]
目前发现一个问题，就是读json文件的时候有字符集的问题，建议用utf-8或者GBK读。我在Windows下面测试名字是乱码。

**Comment by TobisLee** [comment]
哈哈哈 我也是写着玩的 没想到真有人用 
我是在linux下用的 没在windows下测试

**Comment by ForeverOpp** [comment]
> 哈哈哈 我也是写着玩的 没想到真有人用
> 我是在linux下用的 没在windows下测试

那肯定啊，不过现在好多人都是直接办假证——改HTML元素。哈哈大佬可以加Telegram好友么。
那个字符集的问题我已经解决了，就是`with open() as json_file`那里加了一个`encoding="utf-8"`而已。
目前在Windows下运行良好哈哈。
